### ISSUE TITLE
Theme color pallet not fully appearing

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/lifeleck#2]
The color pallet that allows us to change  the theme's color will not fully appear : 
https://prnt.sc/uuhlnj

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
